services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-frontend
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_PUSHER_APP_KEY=${VITE_PUSHER_APP_KEY}
      - VITE_PUSHER_HOST=${VITE_PUSHER_HOST}
      - VITE_PUSHER_PORT=${VITE_PUSHER_PORT}
      - VITE_PUSHER_SCHEME=${VITE_PUSHER_SCHEME}
      - VITE_PUSHER_CLUSTER=${VITE_PUSHER_CLUSTER}
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    command: [ "npm", "run", "dev", "--", "--host", "0.0.0.0" ]
    networks:
      - sail

networks:
  sail:
    external: true